name: Build OpenEuler Image

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ "main" ]

defaults:
  run:
    shell: bash -ileo pipefail {0}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-openeuler-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install qemu and packer
        run: |
          set -eu
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install qemu packer

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build image
        run: |
          set -eux
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          
          packer init ${GITHUB_WORKSPACE}/riscv64-openeuler.pkr.hcl
          packer build -force -color=false ${GITHUB_WORKSPACE}/riscv64-openeuler.pkr.hcl

          rm -rf ${GITHUB_WORKSPACE}/download 

          cp -a ${GITHUB_WORKSPACE}/files/RISCV_VIRT_VARS.fd ${GITHUB_WORKSPACE}/output/
          tar -C ${GITHUB_WORKSPACE}/output/ -czf ${GITHUB_WORKSPACE}/output/openeuler-riscv64-24.03.tar.gz \
            openeuler-riscv64-24.03.qcow2 RISCV_VIRT_VARS.fd

      - name: Package And Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          VERSION=$(date +%Y%m%d)
          
          mvn deploy:deploy-file -B            \
            -DartifactId=openeuler-riscv64     \
            -DgroupId=wang.zhanwei     \
            -Dversion=24.03-${VERSION} \
            -Dpackaging=tar.gz         \
            -DrepositoryId=github      \
            -DgeneratePom=false        \
            -Durl=https://maven.pkg.github.com/wangzw/openeuler-riscv64 \
            -Dfile=${GITHUB_WORKSPACE}/output/openeuler-riscv64-24.03.tar.gz
