name: Build Docker Image

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash -ileo pipefail {0}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  devel-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/wangzw/openeuler-24.03-riscv64
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download qemu image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          VERSION=20240703
          
          mvn dependency:get -B -Dartifact=wang.zhanwei:openeuler-riscv64:24.03-${VERSION}:tar.gz \
            -DremoteRepositories=github::::https://maven.pkg.github.com/wangzw/openeuler-riscv64
          
          mkdir -p ${GITHUB_WORKSPACE}/download
          tar -xzf ~/.m2/repository/wang/zhanwei/openeuler-riscv64/24.03-${VERSION}/openeuler-riscv64-24.03-${VERSION}.tar.gz \
            -C ${GITHUB_WORKSPACE}/download/

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
